[theme]
primaryColor = "#667eea"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 1
cookieSameSite = "strict"

# Security headers
[server.security]
contentSecurityPolicy = "default-src 'self'; script-src 'self' 'unsafe-eval' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; img-src 'self' data: https:; connect-src 'self';"
referrerPolicy = "strict-origin-when-cross-origin"
strictTransportSecurity = "max-age=31536000; includeSubDomains"

[browser]
gatherUsageStats = false